/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SmartFtp;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JustSonny
 */
public class ftpUI extends javax.swing.JFrame {

    /**
     * Creates new form ftpUI
     */
    public ftpUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        runbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dirTujuan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dirAwal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        runbutton.setText("Run");
        runbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runbuttonActionPerformed(evt);
            }
        });

        jLabel5.setText("Example : E:\\efgh\\");

            jLabel2.setText("Destination Directory");

            jLabel4.setText("Example : D:\\abcd\\");

                dirAwal.setAction(dirAwal.getAction());
                dirAwal.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        dirAwalActionPerformed(evt);
                    }
                });

                jLabel1.setText("Source Directory");

                jLabel3.setBackground(new java.awt.Color(255, 255, 255));
                jLabel3.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
                jLabel3.setText("SMART");

                jMenu1.setText("Home");

                jMenuItem1.setText("Exit");
                jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItem1ActionPerformed(evt);
                    }
                });
                jMenu1.add(jMenuItem1);

                jMenuBar1.add(jMenu1);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dirTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dirAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(runbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addContainerGap(132, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dirAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(dirTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(runbutton)
                        .addGap(27, 27, 27))
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void dirAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirAwalActionPerformed

    private void runbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runbuttonActionPerformed
        String awal = this.dirAwal.getText();
        String tujuan = this.dirTujuan.getText();
        //File newFile = new File("D:\\Proyekan\\omahanyar\\sumber\\exec.bat"); 
        File newFile = new File(dirAwal.getText()+"\\exec.bat");// langsung di sikat file exec ditaruh di direkori awal
        if (dirAwal.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Fill Source Directory");
        } else if (dirTujuan.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Fill Destination Directory");
        } else {
        //File newFile = new File("C:/Smart/smart.bat");
        FileWriter wFile = null;
        try {
            wFile = new FileWriter(newFile);
        } catch (IOException ex) {
            Logger.getLogger(ftpUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        Runtime runtime = Runtime.getRuntime();
        
        try (BufferedWriter bw = new BufferedWriter(wFile)) {
            bw.write("set source_drive=");
            bw.write('"'+awal+'"'); //source path parameter diganti input text field
            bw.write("\n");
            bw.write("move %source_drive%\\*.txt ");
            bw.write('"'+tujuan+'"'); //destination path parameter diganti input text field
            bw.write("\n");
            bw.write("timeout /t 5");
            bw.write("\n");
            bw.write("taskkill /im cmd.exe /f");
        } catch (IOException ex) {
            Logger.getLogger(ftpUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("file added");
        System.out.println(dirAwal);
        System.out.println(dirAwal.getText());
        
        if (newFile.exists()) {
            try {    
                newFile.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(ftpUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            newFile.createNewFile();
            }
        catch (IOException e){
            }
        try {
            //runtime.exec("cmd /c start D:/Proyekan/omahanyar/sumber/exec.bat");
            runtime.exec("cmd /c start "+dirAwal.getText()+"/exec.bat");
        }
        catch (IOException e) {}
        }
    }//GEN-LAST:event_runbuttonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ftpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ftpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ftpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ftpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ftpUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dirAwal;
    private javax.swing.JTextField dirTujuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton runbutton;
    // End of variables declaration//GEN-END:variables
}
